community:
  roblox_group_ds: https://www.roblox.com/share/g/945806945
  roblox_group_osec: https://www.roblox.com/communities/288542436/CIA-Office-of-Security#!/about
  roblox_group_grs: https://www.roblox.com/share/g/450710337
  roblox_group_ote: https://www.roblox.com/share/g/1003614105
  discord_invite: https://discord.gg/3S3vDK8nJY
osec:
  information:
    handbook: https://docs.google.com/document/d/1IsygYp9657PKnGqmQyMxTvi50BCJvWVgTaIW7lZPN2U/edit?usp=sharing
    orbat: https://docs.google.com/spreadsheets/d/12pMdf-XiYeHBCX99zO4cmuek8xQr4SL3lAoQcReowWk/edit?usp=sharing
    code_of_agency_conduct: https://docs.google.com/document/d/1McFfJx3IItYHdEdUYdrMT5fiI2spyRu03cif_CyXIZk/edit?usp=sharing
    civilian_access: https://docs.google.com/document/d/1M37oQhF5HF5AUHV4qNMgb2GdhFbv1WxbmRYWsgI5MHo/edit?usp=sharing
  spp_information:
    orientation_guide: https://docs.google.com/document/d/1Q2OF_1MDc_zo0yrL4l51AXLJKjVliDbgBa7nmPf-heM/edit?usp=sharing
    official_handbook: https://docs.google.com/document/d/1IsygYp9657PKnGqmQyMxTvi50BCJvWVgTaIW7lZPN2U/edit?usp=sharing
    code_of_agency_conduct: https://docs.google.com/document/d/1McFfJx3IItYHdEdUYdrMT5fiI2spyRu03cif_CyXIZk/edit?usp=sharing
    civilian_access: https://docs.google.com/document/d/1M37oQhF5HF5AUHV4qNMgb2GdhFbv1WxbmRYWsgI5MHo/edit?usp=sharing
  staff_documents:
    google_drive: https://drive.google.com/drive/folders/1LogIJ8er2ZjD2K39lPtoutdXKDoY2TY5?usp=sharing
    tryout_guide: https://docs.google.com/document/d/1Fc7WK5voKnZ3hKlJQ_2O7ZDQFtht4xOHssqhJcmun30/edit?usp=sharing
    phase_i: https://docs.google.com/document/d/1cGKf1xudnZ85K5oS9_esmXGPhWfGd-R3INE8SAWgcgM/edit?usp=sharing
    phase_ii: https://docs.google.com/document/d/14T05B4HiCdDact6nfTGu2AUk5DnFQYPsfyIe-Dwpb2U/edit?usp=sharing
    standard_training_revamp: https://docs.google.com/document/d/1PQC9MAqWDu1E3SfyFaxfwVfPR9bPUyaLjmEsvznzTyA/edit?usp=sharing
    general_standard_training_guide: https://docs.google.com/document/d/1GV-c5lNL6mcx0Wuf-Jl5D2gT-H7rhgley9dQSMUNs6w/edit?usp=sharing
    weapons_standard_training_guide: https://docs.google.com/document/d/1nXByNDFTpbJe9nqpU6kLoifWaomedmYlo9lqagC2aDE/edit?usp=sharing
    event_guide: https://docs.google.com/document/d/19cl5R83V_hFVrxUB1qOFpWFtV3B0CNXW0VJyETrUIJA/edit?usp=sharing
    base_patrol_event_guide: https://docs.google.com/document/d/1Lst9iRUTUtwJgBJwQz4bBjAhHPShZM3x11EMtlqkdmY/edit?usp=sharing
    killhouse_event_guide: https://docs.google.com/document/d/1DTTVhVso1i5Hy1D3VbPhR-YEoGiZZWu5fFu-VSbmh8o/edit?usp=sharing
    gate_patrol_event_guide: https://docs.google.com/document/d/1VrJb7lhuOoJFDJNY1VzN5jidg0Q-QtNe8ZujcoOnmac/edit?usp=sharing
    combat_training_guide: https://docs.google.com/document/d/12nhTqR41kDZSuftVun0jWjs0PiIvbGA8zez80o3PjYM/edit?usp=sharing
    communications_conduct_certification_guide: https://docs.google.com/document/d/1YqhSGzf3Y5ozGCASrj-9vACDWzodN3rZe0pN9rr43Ew/edit?usp=sharing
    gate_certification_guide: https://docs.google.com/document/d/1hP7mbb8kH1gV56z6TSpmBduurdL6hlInGaefkJoikOE/edit?usp=sharing
    handcuff_certification_guide: https://docs.google.com/document/d/133zQJvT1Slzs7S1Oou6fWpPLz_wdeq0tDr6Kf1z-YAY/edit?usp=sharing
  open_positions:
    lowcom_application: https://forms.gle/SWfWLkmvFr7ZnHMV7
    midcom_application: https://forms.gle/2SZaDfVeUpYDBgAZ6
    application_results_channel: https://discord.com/channels/1442014369507446918/1495761226674733179
    last_updated: June 20th, 2026
ote:
  staff_documents:
    staff_handbook: https://docs.google.com/document/d/1Nhi3xnirH192rIdbMCrGGH5pnhLywQ9EhWxPCoRbY9s/edit?usp=sharing
    staff_database: https://docs.google.com/spreadsheets/d/17Yw1oby46r9pGJXzWSs2cPh3DRaj-ktUQ728GDi09x0/edit?usp=sharing
    tryout_document: https://docs.google.com/document/d/1tNns_L-M1i3SBl7SUwx_Zk1U2Jf8iOU1zRL8zJUnbQQ/edit?usp=drivesdk
    google_drive: https://drive.google.com/drive/folders/11g2H9zeEwFbyO2a6dkxpmSGN0qGR4Oe1?usp=sharing
    general_info_coc: https://docs.google.com/document/d/1gZO3E9X_dbNIjJJQc5wsKgryyH6uTryfjQHLSKbq4EA/edit?usp=sharing
    standard_training_guide: https://docs.google.com/document/d/19M5hFnP5jTy8MlOYUcZ7DqmxAEQN-HDT_thV8TpnaB8/edit?usp=sharing
    weapons_st_guide: https://docs.google.com/document/d/17v8Z-koVCxP2cTopvU8QYJaTaXbBB7RujmPd7tk-Luk/edit?usp=sharing
    graduation_ceremony_procedures: https://docs.google.com/document/d/1NR61wNgfyEnPiDQ7jZB8NwS8CUCFq7nt1aDN2y6uwKA/edit?usp=sharing
  open_positions:
    application: https://docs.google.com/forms/d/e/1FAIpQLSefGwpK9766JHaXw46lqIsbr9VuoVERO90G6LEBE4cdRS4J7g/viewform?usp=header
    application_tracker: https://docs.google.com/spreadsheets/d/1iSOWAM9-Z8WBkdhleuRhbfYa78XC9rMQG7fD3uv6J9c/edit?usp=sharing
  program_overview:
    program_overview: https://docs.google.com/document/d/1UCAJHZYt0rABO0bTRUWcm5euThNKd8otEkAFsfMeJ-c/edit?usp=sharing
    graduation_ceremony_procedures: https://docs.google.com/document/d/1NR61wNgfyEnPiDQ7jZB8NwS8CUCFq7nt1aDN2y6uwKA/edit?usp=sharing
  public_information:
    program_overview: https://docs.google.com/document/d/1UCAJHZYt0rABO0bTRUWcm5euThNKd8otEkAFsfMeJ-c/edit?usp=sharing
grs:
  staff_documents:
    breach_training_guide: https://docs.google.com/document/d/1BopFMmd_0GC2q7k1gLssRJ_RJh6BMAFA3kObdlj407w/edit?usp=sharing
    breaching_certificate: https://docs.google.com/document/d/10VyRbeIE2IMP1qFt6wIZpzN50Iegwpzh0n3dnU_8--c/edit?usp=sharing
    handbook: https://docs.google.com/document/d/1vCBNGn-Vv07FAqVUYle5AFGMy-5yXQJkRDGpYYhBsIU/edit?usp=sharing
    tryout_guide: https://docs.google.com/document/d/1e199RDQlZ2sxU-qgAGB_jBM0ksPb-DVkNmXlburxNA0/edit?usp=sharing
  information:
    handbook: https://docs.google.com/document/d/1vCBNGn-Vv07FAqVUYle5AFGMy-5yXQJkRDGpYYhBsIU/edit?usp=sharing
